include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Additional rules
    prefer_single_quotes: true
    prefer_relative_imports: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    
    # Disable some overly strict rules
    file_names: false
    constant_identifier_names: false
