name: eloqi_mobile
description: "Revolutionary Accent Training App with AI-powered accent twin technology"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Material Design
  cupertino_icons: ^1.0.2
  material_color_utilities: ^0.11.1
  
  # State Management
  provider: ^6.1.2
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Local Storage & Caching
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Audio Recording & Playback
  record: ^6.1.2  # Latest version with improved macOS support
  just_audio: ^0.9.36
  audioplayers: ^5.2.1
  audio_session: ^0.1.21  # For proper audio session configuration
  
  # Permissions
  permission_handler: ^11.1.0
  
  # File Operations
  path_provider: ^2.1.2
  # file_picker: ^6.1.1  # Temporarily removed due to platform implementation issues
  
  # UI Components
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  
  # Charts & Analytics
  fl_chart: ^0.65.0
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  
  # Security
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting & Code Generation
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/audio/
